#!/usr/bin/env bash

set -eu

E_BAD_ARGS=66

lein test :all
lein vcs assert-committed
lein change version leiningen.release/bump-version release
lein vcs commit
lein vcs tag --no-sign --annotate
lein install
lein deploy github
lein change version leiningen.release/bump-version
lein vcs commit

echo "$(cat project.clj | grep defproject | cut -d' ' -f3 | sed 's/\"//g')" > .version
