#!/usr/bin/env bash

set -eu

E_BAD_ARGS=66

lein test :all

lein vcs assert-committed

if [ "$IS_MASTER" = "true" ] ; then
  lein change version leiningen.release/bump-version release
  lein vcs commit
  lein vcs tag --no-sign --annotate
  lein install
fi

lein deploy

if [ "$IS_MASTER" = "true" ] ; then
  echo "$(cat project.clj | grep defproject | cut -d' ' -f3 | sed 's/\"//g')" > .version
  lein change version leiningen.release/bump-version
  lein vcs commit
fi
