#!/usr/bin/env bash

set -eu

E_BAD_ARGS=66

mvn --batch-mode clean
mvn --batch-mode release:prepare
mvn --batch-mode release:perform
mvn --batch-mode help:evaluate -Dexpression=project.version -q -DforceStdout > .version
